import matplotlib.pyplot as plt
from matplotlib import dates
import matplotlib
import pandas as pd
import matplotlib.dates as mdates
import seaborn as sns
import pylab
myFmt = mdates.DateFormatter('%Y')
colours = sns.color_palette("Set2")
colours += sns.color_palette("husl", 9)
colours += sns.color_palette()
temp_df = pd.read_csv('C:/Users/13862/Desktop/ELEC0136_Final_assignment/final-assignment-Zhao-Mingyang-main/Data_Preprocessing/test.csv')
# temp_df = pd.read_csv('C:/Users/13862/Desktop/ELEC0136_Final_assignment/final-assignment-Zhao-Mingyang-main/Before_data.csv')
print(temp_df['Date'])
list_date = pd.to_datetime(temp_df['Date'])
list_date = list_date.tolist()

font = {'size'   : 12}
matplotlib.rc('font', **font)

plt.figure(figsize=(20,16))
ax = pylab.subplot(7,3,1)
ax.xaxis.set_major_locator(dates.YearLocator())
ax.plot_date(list_date, temp_df['Close'], '-', color=colours[0])
ax.xaxis.set_major_formatter(myFmt)
# plt.xticks(rotation=75)
# temp_df['Close'].plot()
plt.title("AAPL Close Price")
plt.grid(visible=True, which='major', axis='both')
ax = pylab.subplot(7,3,2)
ax.xaxis.set_major_locator(dates.YearLocator())
plt.plot_date(list_date , temp_df['Disaster_Affected'], '-', color=colours[1])
ax.xaxis.set_major_formatter(myFmt)
plt.title("Disaster Affected Number")
plt.grid(visible=True, which='major', axis='both')
ax = pylab.subplot(7,3,3)
ax.xaxis.set_major_locator(dates.YearLocator())
plt.plot_date(list_date , temp_df['News_Score'], '-', color=colours[2])
ax.xaxis.set_major_formatter(myFmt)
plt.title("News Score")
plt.grid(visible=True, which='major', axis='both')
ax = pylab.subplot(7,3,4)
ax.xaxis.set_major_locator(dates.YearLocator())
plt.plot_date(list_date , temp_df['Twitter_Score'], '-', color=colours[3])
ax.xaxis.set_major_formatter(myFmt)
plt.title("Twitter Score")
plt.grid(visible=True, which='major', axis='both')
ax = pylab.subplot(7,3,5)
ax.xaxis.set_major_locator(dates.YearLocator())
plt.plot_date(list_date , temp_df['Report_Score'], '-', color=colours[4])
ax.xaxis.set_major_formatter(myFmt)
plt.title("Report Score")
plt.grid(visible=True, which='major', axis='both')
ax = pylab.subplot(7,3,6)
ax.xaxis.set_major_locator(dates.YearLocator())
plt.plot_date(list_date , temp_df['AQI'], '-', color= colours[5])
ax.xaxis.set_major_formatter(myFmt)
plt.title("AQI")
plt.grid(visible=True, which='major', axis='both')
ax = pylab.subplot(7,3,7)
ax.xaxis.set_major_locator(dates.YearLocator())
plt.plot_date(list_date , temp_df['Carbon_Smoothed'], '-', color=colours[6])
ax.xaxis.set_major_formatter(myFmt)
plt.title("Carbon Emission Smoothed Value")
plt.grid(visible=True, which='major', axis='both')
ax = pylab.subplot(7,3,8)
ax.xaxis.set_major_locator(dates.YearLocator())
plt.plot_date(list_date , temp_df['Covid_Index'], '-', color=colours[21])
ax.xaxis.set_major_formatter(myFmt)
plt.title("Covid19")
plt.grid(visible=True, which='major', axis='both')
ax = pylab.subplot(7,3,9)
ax.xaxis.set_major_locator(dates.YearLocator())
plt.plot_date(list_date , temp_df['VIX_Close'], '-', color=colours[20])
ax.xaxis.set_major_formatter(myFmt)
plt.title("VIX CBOE Close Price")
plt.grid(visible=True, which='major', axis='both')

ax = pylab.subplot(7,3,10)
ax.xaxis.set_major_locator(dates.YearLocator())
ax.plot_date(list_date, temp_df['Oil_Close'], '-', color=colours[8])
ax.xaxis.set_major_formatter(myFmt)
plt.title("Oil Price")
plt.grid(visible=True, which='major', axis='both')
ax = pylab.subplot(7,3,11)
ax.xaxis.set_major_locator(dates.YearLocator())
plt.plot_date(list_date , temp_df['Gold_Close'], '-', color=colours[9])
ax.xaxis.set_major_formatter(myFmt)
plt.title("Gold Price")
plt.grid(visible=True, which='major', axis='both')
ax = pylab.subplot(7,3,12)
ax.xaxis.set_major_locator(dates.YearLocator())
plt.plot_date(list_date , temp_df['Silver_Close'], '-', color=colours[10])
ax.xaxis.set_major_formatter(myFmt)
plt.title("Silver Price")
plt.grid(visible=True, which='major', axis='both')
ax = pylab.subplot(7,3,13)
ax.xaxis.set_major_locator(dates.YearLocator())
plt.plot_date(list_date , temp_df['Dollar_Index_Close'], '-', color=colours[11])
ax.xaxis.set_major_formatter(myFmt)
plt.title("Dollar Index")
plt.grid(visible=True, which='major', axis='both')
ax = pylab.subplot(7,3,14)
ax.xaxis.set_major_locator(dates.YearLocator())
plt.plot_date(list_date , temp_df['GBP_Close'], '-', color=colours[12])
ax.xaxis.set_major_formatter(myFmt)
plt.title("GBP")
plt.grid(visible=True, which='major', axis='both')
ax = pylab.subplot(7,3,15)
ax.xaxis.set_major_locator(dates.YearLocator())
plt.plot_date(list_date , temp_df['CNY_Close'], '-', color= colours[13])
ax.xaxis.set_major_formatter(myFmt)
plt.title("CNY")
plt.grid(visible=True, which='major', axis='both')
ax = pylab.subplot(7,3,16)
ax.xaxis.set_major_locator(dates.YearLocator())
plt.plot_date(list_date , temp_df['EUR_Close'], '-', color=colours[14])
ax.xaxis.set_major_formatter(myFmt)
plt.title("EUR")
plt.grid(visible=True, which='major', axis='both')
ax = pylab.subplot(7,3,17)
ax.xaxis.set_major_locator(dates.YearLocator())
plt.plot_date(list_date , temp_df['NASDAQ_Close'], '-', color=colours[15])
ax.xaxis.set_major_formatter(myFmt)
plt.title("NASDAQ")
plt.grid(visible=True, which='major', axis='both')
ax = pylab.subplot(7,3,18)
ax.xaxis.set_major_locator(dates.YearLocator())
plt.plot_date(list_date , temp_df['DJIA_Close'], '-', color=colours[16])
ax.xaxis.set_major_formatter(myFmt)
plt.title("DJIA")
plt.grid(visible=True, which='major', axis='both')
ax = pylab.subplot(7,3,19)
ax.xaxis.set_major_locator(dates.YearLocator())
plt.plot_date(list_date , temp_df['NYA_Close'], '-', color=colours[17])
ax.xaxis.set_major_formatter(myFmt)
plt.title("NYA")
plt.grid(visible=True, which='major', axis='both')
ax = pylab.subplot(7,3,20)
ax.xaxis.set_major_locator(dates.YearLocator())
plt.plot_date(list_date , temp_df['RLG_Close'], '-', color=colours[18])
ax.xaxis.set_major_formatter(myFmt)
plt.title("RLG")
plt.grid(visible=True, which='major', axis='both')
ax = pylab.subplot(7,3,21)
ax.xaxis.set_major_locator(dates.YearLocator())
plt.plot_date(list_date , temp_df['SPX_Close'], '-', color=colours[19])
ax.xaxis.set_major_formatter(myFmt)
plt.title("SPX")
plt.grid(visible=True, which='major', axis='both')
# plt.suptitle("Preprocessed Data (Before Transformation)")
plt.suptitle("Preprocessed Data")
plt.tight_layout()
# plt.savefig('Before_Preprocessed_Data.png')
plt.savefig('Preprocessed_Data2.png')
plt.show()

